#!/bin/sh
set -e

DEFAULT_UID=82
DEFAULT_GID="${DEFAULT_UID}"

# Change UID and GID of www-data to match the host
if [ "${PUID}" -ne "${DEFAULT_UID}" ]; then
    usermod -u ${PUID} www-data
fi
if [ "${PGID}" -ne "${DEFAULT_GID}" ]; then
    groupmod -g ${PGID} www-data
fi

# Change ownership if PUID or PGID differs from the default
if [ "${PUID}" -ne "${DEFAULT_UID}" ] || [ "${PGID}" -ne "${DEFAULT_GID}" ]; then
    chown -R "${PUID}:${PGID}" "${HTTPD_PREFIX}"
fi

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND "$@"
