name: Docker Image CI

on:
  schedule:
  - cron: '5 4 * * 2'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: llaumgui/httpd
  LATEST: '2.4'

jobs:

  ##############################################################################
  # Build job
  #
  build:
    runs-on: ubuntu-latest
    name: Build docker image

    strategy:
      fail-fast: false
      matrix:
        httpd-version: [2.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Login against 2 Docker registries except on PR
    # https://github.com/docker/login-action
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log into registry ${{ env.GHCR_REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.IMAGE_NAME }}
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      if: matrix.httpd-version == ${{ env.LATEST }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.httpd-version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.httpd-version }}
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.httpd-version }}
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        #tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Build and push Docker image
      if: matrix.httpd-version != ${{ env.LATEST }}
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.httpd-version }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.httpd-version }}
          ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.httpd-version }}
        #tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
